from numpy import pi as PI

# figures
FIG_MAPS = 1
FIG_IG_MAPS = 2
FIG_VISIBILITY = 3

DISTANCE_TOLERANCE = 0.005
SIMULATION_SPEED = 100

MAX_TIMESTEPS = 1e6

NUM_ACTORS = 1
NUM_INSTANCES = 12
NUM_EPOCHS = 10

LAMBDA = 0.8
SERVICE_TIME = 0
TICK_TIME = 0.1
BETA = 0.712  # constant for TSP length
WAYPOINT_INTERVAL = 2

EPSILON = 0.000001

WINDOW_SIZE = 60
EGO_X_OFFSET = -WINDOW_SIZE // 2
EGO_Y_OFFSET = -WINDOW_SIZE // 2

LANE_WIDTH = 4
ROAD_WIDTH = 2 * LANE_WIDTH

DEFAULT_POLICY_NAME = "random"
DEFAULT_GENERATOR_NAME = "uniform"
GENERATOR_ARGS = {
    "min": 0,
    "max": 1,
    "seed": None,
    "dim": 2,
    "mix": 0.5,
}

# experiment parameters
V_DES = 8
A_DES = 3.5

ACTOR_SPEED = 6.0
OPPONENT_CAR_SPEED = 6.0
MAX_CAR_SPEED = 9.0
OPPONENT_PEDESTRIAN_SPEED = 1.9
MAX_PEDESTRIAN_SPEED = 1.9
EMERGENCY_BRAKE = -5.0  # m/s/s

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
SCREEN_MARGIN = 120

SCREEN_OUTLINE_COLOUR = (0, 0, 0, 255)
SCREEN_BACKGROUND_COLOUR = (255, 255, 255, 255)
ACTOR_COMPLETE_PATH_COLOUR = (220, 220, 220, 255)
ACTOR_COLOUR = (100, 100, 240, 255)
ACTOR_PATH_COLOUR = (40, 40, 40, 255)
ACTOR_PATH_WIDTH = 3

STATUS_FONT_COLOUR = (0, 0, 0, 255)
STATUS_FONT_SIZE = 32

ROAD_MARKING_COLOUR = (255, 255, 0, 255)
ROAD_COLOUR = (59, 79, 35, 255)

STATUS_Y_SIZE = 100
STATUS_YMARGIN = 8
STATUS_X_SIZE = 300
STATUS_XMARGIN = 16

# Observations are made/delivered on a occupancy grid
GRID_HEIGHT = 60
GRID_WIDTH = 60
GRID_RESOLUTION = 0.5
GRID_ORIGIN_Y_OFFSET = 0
GRID_ORIGIN_X_OFFSET = 0
GRID_SIZE = int(GRID_WIDTH / GRID_RESOLUTION)
OCCUPANCY_THRESHOLD = 0.2

# Fake scanner parameters
SCAN_RANGE = 30
SCAN_RAYS = 800
SCAN_RESOLUTION = 0.05
SCAN_FOV = 2 * PI
SCAN_START_ANGLE = -SCAN_FOV / 2
SCAN_ANGLE_INCREMENT = SCAN_FOV / SCAN_RAYS
SCAN_STDDEV_RANGE = GRID_RESOLUTION / 4

# Constructing a Car lined street (the parkade)
CAR_OFFSET = 1.0
CAR_SPACING = 7.5
CAR_WIGGLE = 1.0
CAR_RATIO = 1.9 / 4.8
CAR_SCALE = 4.8
CAR_ROTATION = 0  # PI / 12

# MPC/MPPI parameters
FORGET_FACTOR = 0.5  # allow the costmap to forget about entries over time
DISCOUNT_FACTOR = 1  # discount cost over the horizon
X_WEIGHT = 50.0
Y_WEIGHT = 250.0
LAMBDA = 20000
V_WEIGHT = 1000
THETA_WEIGHT = 0
DELTA_WEIGHT = 0
ACCEL_VARIATION = 3
OMEGA_VARIATION = PI / 4


# Data capture
RESULTS_DIR = "./results"
